name: salvatara
version: 1.0.8+7
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: ^2.0.15
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_navbar_pro: ^0.0.1
  encrypt: ^5.0.1
  image_picker: ^0.8.6
  tuple: ^2.0.1
  crypto: ^3.0.2
  dotted_border: ^2.0.0+2
  camera: ^0.10.0+4
  contained_tab_bar_view: ^0.8.0
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.1.5
  walletconnect_dart: ^0.0.3
  shimmer: ^2.0.0
  web3dart: ^2.3.5
  http: ^0.13.4
  intl: ^0.17.0
  walletconnect_secure_storage: ^1.0.0
  firebase_core_platform_interface: 4.8.0
  flutter_facebook_auth: ^4.4.1+1
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  firebase_auth: ^4.2.3
  firebase_auth_platform_interface: ^6.10.1
  firebase_core: ^2.4.0
  twitter_login: ^4.2.3
  syncfusion_flutter_charts: ^20.4.38
  flutter_launcher_icons: ^0.11.0
  flutter_simple_candlesticks: ^1.0.2
  candlesticks: ^2.1.0
  dropdown_button2: ^1.9.4
  firebase_dynamic_links: ^5.0.11
  share_plus: ^4.0.4
  rename: ^2.1.1
  file_picker: ^5.2.6
  number_system: ^0.0.6+8
  switcher_button: ^0.0.4
  toasty_snackbar: ^0.0.1
  blinking_text: ^1.0.2
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.2








flutter_icons:
  #image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/SalvataraAppIcon.png"
  image_path_ios: "assets/images/SalvataraAppIcon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter




flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/SVG/
    - assets/SalvataraNFTMarketplace_abi.json
    - assets/SalvaCoinAbi.json

  fonts:
    - family: BlackEcho
      fonts:
        - asset: assets/fonts/BlackEcho.ttf
