///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoinsModelCryptos {
/*
{
  "_id": "63b52a5dca9f6a8d18cb573a",
  "symbol": "btc",
  "name": "Bitcoin",
  "onedaylow": 26716,
  "onedayhigh": 27179,
  "marketCap": 526383138374,
  "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
  "volume": 14857460949,
  "priceUsd": 27125,
  "availableCoins": 19390831,
  "totalCoins": 21000000,
  "about": "",
  "createdAt": "2023-01-04T07:27:25.223Z",
  "updatedAt": "2023-06-02T12:08:21.351Z",
  "price_change_percentage_24h": 0.902,
  "explorer": "https://blockchain.info/",
  "description": "Bitcoin uses peer-to-peer technology to operate with no central authority or banks; managing transactions and the issuing of bitcoins is carried out collectively by the network. Bitcoin is open-source; its design is public, nobody owns or controls Bitcoin and everyone can take part. Through many of its unique properties, Bitcoin allows exciting uses that could not be covered by any previous payment system."
}
*/

  String? Id;
  String? symbol;
  String? name;
  int? onedaylow;
  int? onedayhigh;
  int? marketCap;
  String? image;
  int? volume;
  int? priceUsd;
  int? availableCoins;
  int? totalCoins;
  String? about;
  String? createdAt;
  String? updatedAt;
  double? priceChangePercentage_24h;
  String? explorer;
  String? description;

  CoinsModelCryptos({
    this.Id,
    this.symbol,
    this.name,
    this.onedaylow,
    this.onedayhigh,
    this.marketCap,
    this.image,
    this.volume,
    this.priceUsd,
    this.availableCoins,
    this.totalCoins,
    this.about,
    this.createdAt,
    this.updatedAt,
    this.priceChangePercentage_24h,
    this.explorer,
    this.description,
  });
  CoinsModelCryptos.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    symbol = json['symbol']?.toString();
    name = json['name']?.toString();
    onedaylow = json['onedaylow']?.toInt();
    onedayhigh = json['onedayhigh']?.toInt();
    marketCap = json['marketCap']?.toInt();
    image = json['image']?.toString();
    volume = json['volume']?.toInt();
    priceUsd = json['priceUsd']?.toInt();
    availableCoins = json['availableCoins']?.toInt();
    totalCoins = json['totalCoins']?.toInt();
    about = json['about']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    priceChangePercentage_24h = json['price_change_percentage_24h']?.toDouble();
    explorer = json['explorer']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['symbol'] = symbol;
    data['name'] = name;
    data['onedaylow'] = onedaylow;
    data['onedayhigh'] = onedayhigh;
    data['marketCap'] = marketCap;
    data['image'] = image;
    data['volume'] = volume;
    data['priceUsd'] = priceUsd;
    data['availableCoins'] = availableCoins;
    data['totalCoins'] = totalCoins;
    data['about'] = about;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['price_change_percentage_24h'] = priceChangePercentage_24h;
    data['explorer'] = explorer;
    data['description'] = description;
    return data;
  }
}

class CoinsModel {
/*
{
  "status": true,
  "results": 100,
  "message": "all crypto",
  "Cryptos": [
    {
      "_id": "63b52a5dca9f6a8d18cb573a",
      "symbol": "btc",
      "name": "Bitcoin",
      "onedaylow": 26716,
      "onedayhigh": 27179,
      "marketCap": 526383138374,
      "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
      "volume": 14857460949,
      "priceUsd": 27125,
      "availableCoins": 19390831,
      "totalCoins": 21000000,
      "about": "",
      "createdAt": "2023-01-04T07:27:25.223Z",
      "updatedAt": "2023-06-02T12:08:21.351Z",
      "price_change_percentage_24h": 0.902,
      "explorer": "https://blockchain.info/",
      "description": "Bitcoin uses peer-to-peer technology to operate with no central authority or banks; managing transactions and the issuing of bitcoins is carried out collectively by the network. Bitcoin is open-source; its design is public, nobody owns or controls Bitcoin and everyone can take part. Through many of its unique properties, Bitcoin allows exciting uses that could not be covered by any previous payment system."
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<CoinsModelCryptos?>? Cryptos;

  CoinsModel({
    this.status,
    this.results,
    this.message,
    this.Cryptos,
  });
  CoinsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['Cryptos'] != null) {
      final v = json['Cryptos'];
      final arr0 = <CoinsModelCryptos>[];
      v.forEach((v) {
        arr0.add(CoinsModelCryptos.fromJson(v));
      });
      Cryptos = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (Cryptos != null) {
      final v = Cryptos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['Cryptos'] = arr0;
    }
    return data;
  }
}
