///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CollectionDateUserKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_88D7260C-5A23-4A55-860F-894FC5C5B07B-19088-00000700533D0AFB.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_6D191FA1-9E76-4DD2-8126-874268197E21-19088-00000700615C305A.jpg"
}
*/

  String? documentType;
  String? front;
  String? back;

  CollectionDateUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  CollectionDateUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class CollectionDateUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_88D7260C-5A23-4A55-860F-894FC5C5B07B-19088-00000700533D0AFB.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_6D191FA1-9E76-4DD2-8126-874268197E21-19088-00000700615C305A.jpg"
  },
  "_id": "63a5ad10c2f6161a4052a4b0",
  "email": "yaman@ideausher.com",
  "userType": "partner",
  "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "otp": 0,
  "following": [
    "639842017fc4760970aeba98"
  ],
  "followers": [
    null
  ],
  "followingCount": 1,
  "followersCount": 0,
  "createdAt": "2022-12-23T13:28:48.854Z",
  "updatedAt": "2023-03-27T19:06:16.665Z",
  "walletId": "kjbhb",
  "cor": "India",
  "dob": "2012-01-25T00:00:00.000Z",
  "firstname": "Yaman ",
  "lastname": "Kumar ",
  "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
  "name": "yaman"
}
*/

  CollectionDateUserKyc? kyc;
  String? Id;
  String? email;
  String? userType;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  int? otp;
  List<String?>? following;
  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? walletId;
  String? cor;
  String? dob;
  String? firstname;
  String? lastname;
  String? selfie;
  String? name;

  CollectionDateUser({
    this.kyc,
    this.Id,
    this.email,
    this.userType,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.otp,
    this.following,
    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.walletId,
    this.cor,
    this.dob,
    this.firstname,
    this.lastname,
    this.selfie,
    this.name,
  });
  CollectionDateUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? CollectionDateUserKyc.fromJson(json['kyc']) : null;
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    otp = json['otp']?.toInt();
    if (json['following'] != null) {
      final v = json['following'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      following = arr0;
    }

    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    walletId = json['walletId']?.toString();
    cor = json['cor']?.toString();
    dob = json['dob']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    selfie = json['selfie']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['otp'] = otp;
    if (following != null) {
      final v = following;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['following'] = arr0;
    }

    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['walletId'] = walletId;
    data['cor'] = cor;
    data['dob'] = dob;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['selfie'] = selfie;
    data['name'] = name;
    return data;
  }
}

class CollectionDate {
/*
{
  "_id": "64255f8af3999cf71bdb971a",
  "title": "collection1",
  "category": "png",
  "description": "collection description",
  "externalLink": "https://www.collection.io",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "profile link",
  "cover": "cover link",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_88D7260C-5A23-4A55-860F-894FC5C5B07B-19088-00000700533D0AFB.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_6D191FA1-9E76-4DD2-8126-874268197E21-19088-00000700615C305A.jpg"
    },
    "_id": "63a5ad10c2f6161a4052a4b0",
    "email": "yaman@ideausher.com",
    "userType": "partner",
    "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "otp": 0,
    "following": [
      "639842017fc4760970aeba98"
    ],
    "followers": [
      null
    ],
    "followingCount": 1,
    "followersCount": 0,
    "createdAt": "2022-12-23T13:28:48.854Z",
    "updatedAt": "2023-03-27T19:06:16.665Z",
    "walletId": "kjbhb",
    "cor": "India",
    "dob": "2012-01-25T00:00:00.000Z",
    "firstname": "Yaman ",
    "lastname": "Kumar ",
    "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
    "name": "yaman"
  },
  "volume": 0,
  "price": null
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  CollectionDateUser? user;
  int? volume;
  String? price;

  CollectionDate({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.volume,
    this.price,
  });
  CollectionDate.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? CollectionDateUser.fromJson(json['user']) : null;
    volume = json['volume']?.toInt();
    price = json['price']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['volume'] = volume;
    data['price'] = price;
    return data;
  }
}

class Collection {
/*
{
  "status": true,
  "message": "collection list",
  "date": [
    {
      "_id": "64255f8af3999cf71bdb971a",
      "title": "collection1",
      "category": "png",
      "description": "collection description",
      "externalLink": "https://www.collection.io",
      "explicit_sensitive": true,
      "royalty": 1,
      "profile": "profile link",
      "cover": "cover link",
      "user": {
        "kyc": {
          "documentType": "document",
          "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_88D7260C-5A23-4A55-860F-894FC5C5B07B-19088-00000700533D0AFB.png",
          "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_6D191FA1-9E76-4DD2-8126-874268197E21-19088-00000700615C305A.jpg"
        },
        "_id": "63a5ad10c2f6161a4052a4b0",
        "email": "yaman@ideausher.com",
        "userType": "partner",
        "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
        "firebaseSignInProvider": "password",
        "active": true,
        "isDeleted": false,
        "otp": 0,
        "following": [
          "639842017fc4760970aeba98"
        ],
        "followers": [
          null
        ],
        "followingCount": 1,
        "followersCount": 0,
        "createdAt": "2022-12-23T13:28:48.854Z",
        "updatedAt": "2023-03-27T19:06:16.665Z",
        "walletId": "kjbhb",
        "cor": "India",
        "dob": "2012-01-25T00:00:00.000Z",
        "firstname": "Yaman ",
        "lastname": "Kumar ",
        "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
        "name": "yaman"
      },
      "volume": 0,
      "price": null
    }
  ]
}
*/

  bool? status;
  String? message;
  List<CollectionDate?>? date;

  Collection({
    this.status,
    this.message,
    this.date,
  });
  Collection.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['date'] != null) {
      final v = json['date'];
      final arr0 = <CollectionDate>[];
      v.forEach((v) {
        arr0.add(CollectionDate.fromJson(v));
      });
      date = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (date != null) {
      final v = date;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['date'] = arr0;
    }
    return data;
  }
}
