///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CollectedNFTDataNftIdCollectionIdUserKyc {
/*
{
  "documentType": "document",
  "front": "hj",
  "back": "hj"
}
*/

  String? documentType;
  String? front;
  String? back;

  CollectedNFTDataNftIdCollectionIdUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  CollectedNFTDataNftIdCollectionIdUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class CollectedNFTDataNftIdCollectionIdUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "hj",
    "back": "hj"
  },
  "_id": "63a5ad10c2f6161a4052a4b0",
  "email": "yaman@ideausher.com",
  "userType": "partner",
  "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "otp": 0,
  "following": [
    "639842017fc4760970aeba98"
  ],
  "followers": [
    null
  ],
  "followingCount": 1,
  "followersCount": 0,
  "createdAt": "2022-12-23T13:28:48.854Z",
  "updatedAt": "2023-02-27T06:43:14.541Z",
  "walletId": "kjbhb",
  "cor": "hjkk",
  "dob": "2022-12-12T07:46:32.733Z",
  "firstname": "salvatara",
  "lastname": "tseting",
  "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
  "name": "yaman"
}
*/

  CollectedNFTDataNftIdCollectionIdUserKyc? kyc;
  String? Id;
  String? email;
  String? userType;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  int? otp;
  List<String?>? following;

  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? walletId;
  String? cor;
  String? dob;
  String? firstname;
  String? lastname;
  String? selfie;
  String? name;

  CollectedNFTDataNftIdCollectionIdUser({
    this.kyc,
    this.Id,
    this.email,
    this.userType,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.otp,
    this.following,

    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.walletId,
    this.cor,
    this.dob,
    this.firstname,
    this.lastname,
    this.selfie,
    this.name,
  });
  CollectedNFTDataNftIdCollectionIdUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? CollectedNFTDataNftIdCollectionIdUserKyc.fromJson(json['kyc']) : null;
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    otp = json['otp']?.toInt();
    if (json['following'] != null) {
      final v = json['following'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      following = arr0;
    }

    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    walletId = json['walletId']?.toString();
    cor = json['cor']?.toString();
    dob = json['dob']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    selfie = json['selfie']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['otp'] = otp;
    if (following != null) {
      final v = following;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['following'] = arr0;
    }

    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['walletId'] = walletId;
    data['cor'] = cor;
    data['dob'] = dob;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['selfie'] = selfie;
    data['name'] = name;
    return data;
  }
}

class CollectedNFTDataNftIdCollectionId {
/*
{
  "_id": "6405bc5781c8351497284a80",
  "title": "collection1",
  "category": "png",
  "description": "collection description",
  "externalLink": "https://www.collection.io",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "profile link",
  "cover": "cover link",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "hj",
      "back": "hj"
    },
    "_id": "63a5ad10c2f6161a4052a4b0",
    "email": "yaman@ideausher.com",
    "userType": "partner",
    "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "otp": 0,
    "following": [
      "639842017fc4760970aeba98"
    ],
    "followers": [
      null
    ],
    "followingCount": 1,
    "followersCount": 0,
    "createdAt": "2022-12-23T13:28:48.854Z",
    "updatedAt": "2023-02-27T06:43:14.541Z",
    "walletId": "kjbhb",
    "cor": "hjkk",
    "dob": "2022-12-12T07:46:32.733Z",
    "firstname": "salvatara",
    "lastname": "tseting",
    "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
    "name": "yaman"
  },
  "createdAt": "2023-03-06T10:11:35.414Z",
  "updatedAt": "2023-03-06T10:11:35.414Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  CollectedNFTDataNftIdCollectionIdUser? user;
  String? createdAt;
  String? updatedAt;

  CollectedNFTDataNftIdCollectionId({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.createdAt,
    this.updatedAt,
  });
  CollectedNFTDataNftIdCollectionId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? CollectedNFTDataNftIdCollectionIdUser.fromJson(json['user']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class CollectedNFTDataNftId {
/*
{
  "_id": "6405dba0146b863f2c4a1a95",
  "title": "Doddles",
  "category": "png",
  "description": "Doddles",
  "price": 0.01,
  "externalLink": "qwerty",
  "explicit_sensitive": true,
  "stats": true,
  "royalty": 2,
  "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryDoodles-1.png",
  "fileType": "image",
  "market": "setPrice",
  "status": "Sold",
  "collectionId": {
    "_id": "6405bc5781c8351497284a80",
    "title": "collection1",
    "category": "png",
    "description": "collection description",
    "externalLink": "https://www.collection.io",
    "explicit_sensitive": true,
    "royalty": 1,
    "profile": "profile link",
    "cover": "cover link",
    "user": {
      "kyc": {
        "documentType": "document",
        "front": "hj",
        "back": "hj"
      },
      "_id": "63a5ad10c2f6161a4052a4b0",
      "email": "yaman@ideausher.com",
      "userType": "partner",
      "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
      "firebaseSignInProvider": "password",
      "active": true,
      "isDeleted": false,
      "otp": 0,
      "following": [
        "639842017fc4760970aeba98"
      ],
      "followers": [
        null
      ],
      "followingCount": 1,
      "followersCount": 0,
      "createdAt": "2022-12-23T13:28:48.854Z",
      "updatedAt": "2023-02-27T06:43:14.541Z",
      "walletId": "kjbhb",
      "cor": "hjkk",
      "dob": "2022-12-12T07:46:32.733Z",
      "firstname": "salvatara",
      "lastname": "tseting",
      "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
      "name": "yaman"
    },
    "createdAt": "2023-03-06T10:11:35.414Z",
    "updatedAt": "2023-03-06T10:11:35.414Z"
  },
  "owner": "63a5ad10c2f6161a4052a4b0",
  "views": 0,
  "favourites": 0,
  "tokenId": "41",
  "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
  "platFormFee": 0,
  "createdAt": "2023-03-06T12:25:04.873Z",
  "updatedAt": "2023-03-06T12:31:36.909Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  double? price;
  String? externalLink;
  bool? explicitSensitive;
  bool? stats;
  int? royalty;
  String? imageURL;
  String? fileType;
  String? market;
  String? status;
  CollectedNFTDataNftIdCollectionId? collectionId;
  String? owner;
  int? views;
  int? favourites;
  String? tokenId;
  String? contractAddress;
  int? platFormFee;
  String? createdAt;
  String? updatedAt;

  CollectedNFTDataNftId({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.price,
    this.externalLink,
    this.explicitSensitive,
    this.stats,
    this.royalty,
    this.imageURL,
    this.fileType,
    this.market,
    this.status,
    this.collectionId,
    this.owner,
    this.views,
    this.favourites,
    this.tokenId,
    this.contractAddress,
    this.platFormFee,
    this.createdAt,
    this.updatedAt,
  });
  CollectedNFTDataNftId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toDouble();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    stats = json['stats'];
    royalty = json['royalty']?.toInt();
    imageURL = json['imageURL']?.toString();
    fileType = json['fileType']?.toString();
    market = json['market']?.toString();
    status = json['status']?.toString();
    collectionId = (json['collectionId'] != null) ? CollectedNFTDataNftIdCollectionId.fromJson(json['collectionId']) : null;
    owner = json['owner']?.toString();
    views = json['views']?.toInt();
    favourites = json['favourites']?.toInt();
    tokenId = json['tokenId']?.toString();
    contractAddress = json['contractAddress']?.toString();
    platFormFee = json['platFormFee']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['price'] = price;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['stats'] = stats;
    data['royalty'] = royalty;
    data['imageURL'] = imageURL;
    data['fileType'] = fileType;
    data['market'] = market;
    data['status'] = status;
    if (collectionId != null) {
      data['collectionId'] = collectionId!.toJson();
    }
    data['owner'] = owner;
    data['views'] = views;
    data['favourites'] = favourites;
    data['tokenId'] = tokenId;
    data['contractAddress'] = contractAddress;
    data['platFormFee'] = platFormFee;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class CollectedNFTDataUserIdKyc {
/*
{
  "documentType": "document",
  "front": "hj",
  "back": "hj"
}
*/

  String? documentType;
  String? front;
  String? back;

  CollectedNFTDataUserIdKyc({
    this.documentType,
    this.front,
    this.back,
  });
  CollectedNFTDataUserIdKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class CollectedNFTDataUserId {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "hj",
    "back": "hj"
  },
  "_id": "63a5ad10c2f6161a4052a4b0",
  "email": "yaman@ideausher.com",
  "userType": "partner",
  "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "otp": 0,
  "following": [
    "639842017fc4760970aeba98"
  ],
  "followers": [
    null
  ],
  "followingCount": 1,
  "followersCount": 0,
  "createdAt": "2022-12-23T13:28:48.854Z",
  "updatedAt": "2023-02-27T06:43:14.541Z",
  "walletId": "kjbhb",
  "cor": "hjkk",
  "dob": "2022-12-12T07:46:32.733Z",
  "firstname": "salvatara",
  "lastname": "tseting",
  "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
  "name": "yaman"
}
*/

  CollectedNFTDataUserIdKyc? kyc;
  String? Id;
  String? email;
  String? userType;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  int? otp;
  List<String?>? following;

  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? walletId;
  String? cor;
  String? dob;
  String? firstname;
  String? lastname;
  String? selfie;
  String? name;

  CollectedNFTDataUserId({
    this.kyc,
    this.Id,
    this.email,
    this.userType,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.otp,
    this.following,

    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.walletId,
    this.cor,
    this.dob,
    this.firstname,
    this.lastname,
    this.selfie,
    this.name,
  });
  CollectedNFTDataUserId.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? CollectedNFTDataUserIdKyc.fromJson(json['kyc']) : null;
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    otp = json['otp']?.toInt();
    if (json['following'] != null) {
      final v = json['following'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      following = arr0;
    }

    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    walletId = json['walletId']?.toString();
    cor = json['cor']?.toString();
    dob = json['dob']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
    selfie = json['selfie']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['otp'] = otp;
    if (following != null) {
      final v = following;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['following'] = arr0;
    }

    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['walletId'] = walletId;
    data['cor'] = cor;
    data['dob'] = dob;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    data['selfie'] = selfie;
    data['name'] = name;
    return data;
  }
}

class CollectedNFTData {
/*
{
  "userId": {
    "kyc": {
      "documentType": "document",
      "front": "hj",
      "back": "hj"
    },
    "_id": "63a5ad10c2f6161a4052a4b0",
    "email": "yaman@ideausher.com",
    "userType": "partner",
    "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "otp": 0,
    "following": [
      "639842017fc4760970aeba98"
    ],
    "followers": [
      null
    ],
    "followingCount": 1,
    "followersCount": 0,
    "createdAt": "2022-12-23T13:28:48.854Z",
    "updatedAt": "2023-02-27T06:43:14.541Z",
    "walletId": "kjbhb",
    "cor": "hjkk",
    "dob": "2022-12-12T07:46:32.733Z",
    "firstname": "salvatara",
    "lastname": "tseting",
    "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
    "name": "yaman"
  },
  "nftId": [
    {
      "_id": "6405dba0146b863f2c4a1a95",
      "title": "Doddles",
      "category": "png",
      "description": "Doddles",
      "price": 0.01,
      "externalLink": "qwerty",
      "explicit_sensitive": true,
      "stats": true,
      "royalty": 2,
      "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryDoodles-1.png",
      "fileType": "image",
      "market": "setPrice",
      "status": "Sold",
      "collectionId": {
        "_id": "6405bc5781c8351497284a80",
        "title": "collection1",
        "category": "png",
        "description": "collection description",
        "externalLink": "https://www.collection.io",
        "explicit_sensitive": true,
        "royalty": 1,
        "profile": "profile link",
        "cover": "cover link",
        "user": {
          "kyc": {
            "documentType": "document",
            "front": "hj",
            "back": "hj"
          },
          "_id": "63a5ad10c2f6161a4052a4b0",
          "email": "yaman@ideausher.com",
          "userType": "partner",
          "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
          "firebaseSignInProvider": "password",
          "active": true,
          "isDeleted": false,
          "otp": 0,
          "following": [
            "639842017fc4760970aeba98"
          ],
          "followers": [
            null
          ],
          "followingCount": 1,
          "followersCount": 0,
          "createdAt": "2022-12-23T13:28:48.854Z",
          "updatedAt": "2023-02-27T06:43:14.541Z",
          "walletId": "kjbhb",
          "cor": "hjkk",
          "dob": "2022-12-12T07:46:32.733Z",
          "firstname": "salvatara",
          "lastname": "tseting",
          "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
          "name": "yaman"
        },
        "createdAt": "2023-03-06T10:11:35.414Z",
        "updatedAt": "2023-03-06T10:11:35.414Z"
      },
      "owner": "63a5ad10c2f6161a4052a4b0",
      "views": 0,
      "favourites": 0,
      "tokenId": "41",
      "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
      "platFormFee": 0,
      "createdAt": "2023-03-06T12:25:04.873Z",
      "updatedAt": "2023-03-06T12:31:36.909Z"
    }
  ]
}
*/

  CollectedNFTDataUserId? userId;
  List<CollectedNFTDataNftId?>? nftId;

  CollectedNFTData({
    this.userId,
    this.nftId,
  });
  CollectedNFTData.fromJson(Map<String, dynamic> json) {
    userId = (json['userId'] != null) ? CollectedNFTDataUserId.fromJson(json['userId']) : null;
    if (json['nftId'] != null) {
      final v = json['nftId'];
      final arr0 = <CollectedNFTDataNftId>[];
      v.forEach((v) {
        arr0.add(CollectedNFTDataNftId.fromJson(v));
      });
      nftId = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (userId != null) {
      data['userId'] = userId!.toJson();
    }
    if (nftId != null) {
      final v = nftId;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['nftId'] = arr0;
    }
    return data;
  }
}

class CollectedNFT {
/*
{
  "status": true,
  "message": "user collection list",
  "data": {
    "userId": {
      "kyc": {
        "documentType": "document",
        "front": "hj",
        "back": "hj"
      },
      "_id": "63a5ad10c2f6161a4052a4b0",
      "email": "yaman@ideausher.com",
      "userType": "partner",
      "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
      "firebaseSignInProvider": "password",
      "active": true,
      "isDeleted": false,
      "otp": 0,
      "following": [
        "639842017fc4760970aeba98"
      ],
      "followers": [
        null
      ],
      "followingCount": 1,
      "followersCount": 0,
      "createdAt": "2022-12-23T13:28:48.854Z",
      "updatedAt": "2023-02-27T06:43:14.541Z",
      "walletId": "kjbhb",
      "cor": "hjkk",
      "dob": "2022-12-12T07:46:32.733Z",
      "firstname": "salvatara",
      "lastname": "tseting",
      "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
      "name": "yaman"
    },
    "nftId": [
      {
        "_id": "6405dba0146b863f2c4a1a95",
        "title": "Doddles",
        "category": "png",
        "description": "Doddles",
        "price": 0.01,
        "externalLink": "qwerty",
        "explicit_sensitive": true,
        "stats": true,
        "royalty": 2,
        "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryDoodles-1.png",
        "fileType": "image",
        "market": "setPrice",
        "status": "Sold",
        "collectionId": {
          "_id": "6405bc5781c8351497284a80",
          "title": "collection1",
          "category": "png",
          "description": "collection description",
          "externalLink": "https://www.collection.io",
          "explicit_sensitive": true,
          "royalty": 1,
          "profile": "profile link",
          "cover": "cover link",
          "user": {
            "kyc": {
              "documentType": "document",
              "front": "hj",
              "back": "hj"
            },
            "_id": "63a5ad10c2f6161a4052a4b0",
            "email": "yaman@ideausher.com",
            "userType": "partner",
            "firebaseUid": "2FmAPc8o8DhLHmiZFDkLT466KdI2",
            "firebaseSignInProvider": "password",
            "active": true,
            "isDeleted": false,
            "otp": 0,
            "following": [
              "639842017fc4760970aeba98"
            ],
            "followers": [
              null
            ],
            "followingCount": 1,
            "followersCount": 0,
            "createdAt": "2022-12-23T13:28:48.854Z",
            "updatedAt": "2023-02-27T06:43:14.541Z",
            "walletId": "kjbhb",
            "cor": "hjkk",
            "dob": "2022-12-12T07:46:32.733Z",
            "firstname": "salvatara",
            "lastname": "tseting",
            "selfie": "https://media.istockphoto.com/id/475836292/photo/clouds-rolling-between-hills-of-himachal.jpg?s=612x612&w=0&k=20&c=orTwGIhfXYnJPMpnkq70AL5IQPSLj0XeLVgn-EjjdyM=",
            "name": "yaman"
          },
          "createdAt": "2023-03-06T10:11:35.414Z",
          "updatedAt": "2023-03-06T10:11:35.414Z"
        },
        "owner": "63a5ad10c2f6161a4052a4b0",
        "views": 0,
        "favourites": 0,
        "tokenId": "41",
        "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
        "platFormFee": 0,
        "createdAt": "2023-03-06T12:25:04.873Z",
        "updatedAt": "2023-03-06T12:31:36.909Z"
      }
    ]
  }
}
*/

  bool? status;
  String? message;
  CollectedNFTData? data;

  CollectedNFT({
    this.status,
    this.message,
    this.data,
  });
  CollectedNFT.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? CollectedNFTData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
