///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class getUserKycDetailsData {
/*
{
  "personalInfo": true,
  "selfie": true,
  "kycDocument": true
}
*/

  bool? personalInfo;
  bool? selfie;
  bool? kycDocument;

  getUserKycDetailsData({
    this.personalInfo,
    this.selfie,
    this.kycDocument,
  });
  getUserKycDetailsData.fromJson(Map<String, dynamic> json) {
    personalInfo = json['personalInfo'];
    selfie = json['selfie'];
    kycDocument = json['kycDocument'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['personalInfo'] = personalInfo;
    data['selfie'] = selfie;
    data['kycDocument'] = kycDocument;
    return data;
  }
}

class getUserKycDetails {
/*
{
  "status": true,
  "message": "kyc details",
  "data": {
    "personalInfo": true,
    "selfie": true,
    "kycDocument": true
  }
}
*/

  bool? status;
  String? message;
  getUserKycDetailsData? data;

  getUserKycDetails({
    this.status,
    this.message,
    this.data,
  });
  getUserKycDetails.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? getUserKycDetailsData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
