///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class coinOneDataDataSimilar {
/*
{
  "_id": "63aeed46348235a6639a9ec2",
  "rank": 1,
  "symbol": "BTC",
  "name": "Bitcoin",
  "supply": 320253980517.413,
  "maxSupply": "320253980517.413",
  "marketCapUsd": 320253980517.413,
  "volumeUsd24Hr": 320253980517.413,
  "priceUsd": 320253980517.413,
  "changePercent24Hr": 320253980517.413,
  "vwap24Hr": 320253980517.413,
  "explorer": "https://blockchain.info/",
  "createdAt": "2022-12-30T13:53:10.866Z",
  "updatedAt": "2023-01-02T06:21:38.727Z"
}
*/

  String? Id;
  int? rank;
  String? symbol;
  String? name;
  double? supply;
  String? maxSupply;
  double? marketCapUsd;
  double? volumeUsd24Hr;
  double? priceUsd;
  double? changePercent24Hr;
  double? vwap24Hr;
  String? explorer;
  String? createdAt;
  String? updatedAt;

  coinOneDataDataSimilar({
    this.Id,
    this.rank,
    this.symbol,
    this.name,
    this.supply,
    this.maxSupply,
    this.marketCapUsd,
    this.volumeUsd24Hr,
    this.priceUsd,
    this.changePercent24Hr,
    this.vwap24Hr,
    this.explorer,
    this.createdAt,
    this.updatedAt,
  });
  coinOneDataDataSimilar.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    rank = json['rank']?.toInt();
    symbol = json['symbol']?.toString();
    name = json['name']?.toString();
    supply = json['supply']?.toDouble();
    maxSupply = json['maxSupply']?.toString();
    marketCapUsd = json['marketCapUsd']?.toDouble();
    volumeUsd24Hr = json['volumeUsd24Hr']?.toDouble();
    priceUsd = json['priceUsd']?.toDouble();
    changePercent24Hr = json['changePercent24Hr']?.toDouble();
    vwap24Hr = json['vwap24Hr']?.toDouble();
    explorer = json['explorer']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['rank'] = rank;
    data['symbol'] = symbol;
    data['name'] = name;
    data['supply'] = supply;
    data['maxSupply'] = maxSupply;
    data['marketCapUsd'] = marketCapUsd;
    data['volumeUsd24Hr'] = volumeUsd24Hr;
    data['priceUsd'] = priceUsd;
    data['changePercent24Hr'] = changePercent24Hr;
    data['vwap24Hr'] = vwap24Hr;
    data['explorer'] = explorer;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class coinOneDataData {
/*
{
  "id": "polkadot",
  "rank": 12,
  "symbol": "DOT",
  "name": "Polkadot",
  "supply": 5279018214.754,
  "maxSupply": 5279018214.754,
  "marketCapUsd": 5279018214.754,
  "volumeUsd24Hr": 5279018214.754,
  "priceUsd": 5279018214.754,
  "changePercent24Hr": 5279018214.754,
  "vwap24Hr": 5279018214.754,
  "explorer": "https://polkascan.io/polkadot",
  "about": "",
  "similar": [
    {
      "_id": "63aeed46348235a6639a9ec2",
      "rank": 1,
      "symbol": "BTC",
      "name": "Bitcoin",
      "supply": 320253980517.413,
      "maxSupply": "320253980517.413",
      "marketCapUsd": 320253980517.413,
      "volumeUsd24Hr": 320253980517.413,
      "priceUsd": 320253980517.413,
      "changePercent24Hr": 320253980517.413,
      "vwap24Hr": 320253980517.413,
      "explorer": "https://blockchain.info/",
      "createdAt": "2022-12-30T13:53:10.866Z",
      "updatedAt": "2023-01-02T06:21:38.727Z"
    }
  ]
}
*/

  String? id;
  int? rank;
  String? symbol;
  String? name;
  double? supply;
  double? maxSupply;
  double? marketCapUsd;
  double? volumeUsd24Hr;
  double? priceUsd;
  double? changePercent24Hr;
  double? vwap24Hr;
  String? explorer;
  String? about;
  List<coinOneDataDataSimilar?>? similar;

  coinOneDataData({
    this.id,
    this.rank,
    this.symbol,
    this.name,
    this.supply,
    this.maxSupply,
    this.marketCapUsd,
    this.volumeUsd24Hr,
    this.priceUsd,
    this.changePercent24Hr,
    this.vwap24Hr,
    this.explorer,
    this.about,
    this.similar,
  });
  coinOneDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    rank = json['rank']?.toInt();
    symbol = json['symbol']?.toString();
    name = json['name']?.toString();
    supply = json['supply']?.toDouble();
    maxSupply = json['maxSupply']?.toDouble();
    marketCapUsd = json['marketCapUsd']?.toDouble();
    volumeUsd24Hr = json['volumeUsd24Hr']?.toDouble();
    priceUsd = json['priceUsd']?.toDouble();
    changePercent24Hr = json['changePercent24Hr']?.toDouble();
    vwap24Hr = json['vwap24Hr']?.toDouble();
    explorer = json['explorer']?.toString();
    about = json['about']?.toString();
    if (json['similar'] != null) {
      final v = json['similar'];
      final arr0 = <coinOneDataDataSimilar>[];
      v.forEach((v) {
        arr0.add(coinOneDataDataSimilar.fromJson(v));
      });
      similar = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['rank'] = rank;
    data['symbol'] = symbol;
    data['name'] = name;
    data['supply'] = supply;
    data['maxSupply'] = maxSupply;
    data['marketCapUsd'] = marketCapUsd;
    data['volumeUsd24Hr'] = volumeUsd24Hr;
    data['priceUsd'] = priceUsd;
    data['changePercent24Hr'] = changePercent24Hr;
    data['vwap24Hr'] = vwap24Hr;
    data['explorer'] = explorer;
    data['about'] = about;
    if (similar != null) {
      final v = similar;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['similar'] = arr0;
    }
    return data;
  }
}

class coinOneData {
/*
{
  "status": true,
  "message": "Crypto Data",
  "data": {
    "id": "polkadot",
    "rank": 12,
    "symbol": "DOT",
    "name": "Polkadot",
    "supply": 5279018214.754,
    "maxSupply": 5279018214.754,
    "marketCapUsd": 5279018214.754,
    "volumeUsd24Hr": 5279018214.754,
    "priceUsd": 5279018214.754,
    "changePercent24Hr": 5279018214.754,
    "vwap24Hr": 5279018214.754,
    "explorer": "https://polkascan.io/polkadot",
    "about": "",
    "similar": [
      {
        "_id": "63aeed46348235a6639a9ec2",
        "rank": 1,
        "symbol": "BTC",
        "name": "Bitcoin",
        "supply": 320253980517.413,
        "maxSupply": "320253980517.413",
        "marketCapUsd": 320253980517.413,
        "volumeUsd24Hr": 320253980517.413,
        "priceUsd": 320253980517.413,
        "changePercent24Hr": 320253980517.413,
        "vwap24Hr": 320253980517.413,
        "explorer": "https://blockchain.info/",
        "createdAt": "2022-12-30T13:53:10.866Z",
        "updatedAt": "2023-01-02T06:21:38.727Z"
      }
    ]
  }
}
*/

  bool? status;
  String? message;
  coinOneDataData? data;

  coinOneData({
    this.status,
    this.message,
    this.data,
  });
  coinOneData.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? coinOneDataData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
