///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OneCollectionModelDateNftCollectionIdUserKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
}
*/

  String? documentType;
  String? front;
  String? back;

  OneCollectionModelDateNftCollectionIdUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  OneCollectionModelDateNftCollectionIdUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class OneCollectionModelDateNftCollectionIdUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
  },
  "name": "",
  "walletId": "",
  "_id": "63c9488150546b2606610c11",
  "email": "yamankumar112@gmail.com",
  "userType": "admin",
  "cor": "India ",
  "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "dob": "2012-02-16T00:00:00.000Z",
  "otp": 0,
  "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
  "following": [
    null
  ],
  "followers": [
    null
  ],
  "followingCount": 0,
  "followersCount": 0,
  "createdAt": "2023-01-19T13:41:21.855Z",
  "updatedAt": "2023-03-29T22:05:59.587Z",
  "firstname": "Yaman",
  "lastname": "Kumar "
}
*/

  OneCollectionModelDateNftCollectionIdUserKyc? kyc;
  String? name;
  String? walletId;
  String? Id;
  String? email;
  String? userType;
  String? cor;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? dob;
  int? otp;
  String? selfie;
  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? firstname;
  String? lastname;

  OneCollectionModelDateNftCollectionIdUser({
    this.kyc,
    this.name,
    this.walletId,
    this.Id,
    this.email,
    this.userType,
    this.cor,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.dob,
    this.otp,
    this.selfie,
    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.firstname,
    this.lastname,
  });
  OneCollectionModelDateNftCollectionIdUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? OneCollectionModelDateNftCollectionIdUserKyc.fromJson(json['kyc']) : null;
    name = json['name']?.toString();
    walletId = json['walletId']?.toString();
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    cor = json['cor']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    dob = json['dob']?.toString();
    otp = json['otp']?.toInt();
    selfie = json['selfie']?.toString();
    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['name'] = name;
    data['walletId'] = walletId;
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['cor'] = cor;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['dob'] = dob;
    data['otp'] = otp;
    data['selfie'] = selfie;
    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class OneCollectionModelDateNftCollectionId {
/*
{
  "_id": "642ab7435b1e596fb7376664",
  "title": "Minted queens ",
  "category": "png",
  "description": "Minted queens ",
  "externalLink": "www",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
  "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
    },
    "name": "",
    "walletId": "",
    "_id": "63c9488150546b2606610c11",
    "email": "yamankumar112@gmail.com",
    "userType": "admin",
    "cor": "India ",
    "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "dob": "2012-02-16T00:00:00.000Z",
    "otp": 0,
    "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
    "following": [
      null
    ],
    "followers": [
      null
    ],
    "followingCount": 0,
    "followersCount": 0,
    "createdAt": "2023-01-19T13:41:21.855Z",
    "updatedAt": "2023-03-29T22:05:59.587Z",
    "firstname": "Yaman",
    "lastname": "Kumar "
  },
  "createdAt": "2023-04-03T11:23:47.150Z",
  "updatedAt": "2023-04-03T11:23:47.150Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  OneCollectionModelDateNftCollectionIdUser? user;
  String? createdAt;
  String? updatedAt;

  OneCollectionModelDateNftCollectionId({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.createdAt,
    this.updatedAt,
  });
  OneCollectionModelDateNftCollectionId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? OneCollectionModelDateNftCollectionIdUser.fromJson(json['user']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class OneCollectionModelDateNft {
/*
{
  "_id": "642abd9d5b1e596fb7376750",
  "title": "RED ",
  "category": "png",
  "description": "desc",
  "price": 0.01,
  "externalLink": "www",
  "explicit_sensitive": true,
  "stats": true,
  "royalty": 10,
  "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_E211332C-C9DB-45C0-BC58-494A2803C75A-2281-0000010F2F506E37.jpg",
  "fileType": "image",
  "market": "setPrice",
  "status": "Listed",
  "collectionId": {
    "_id": "642ab7435b1e596fb7376664",
    "title": "Minted queens ",
    "category": "png",
    "description": "Minted queens ",
    "externalLink": "www",
    "explicit_sensitive": true,
    "royalty": 1,
    "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
    "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
    "user": {
      "kyc": {
        "documentType": "document",
        "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
        "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
      },
      "name": "",
      "walletId": "",
      "_id": "63c9488150546b2606610c11",
      "email": "yamankumar112@gmail.com",
      "userType": "admin",
      "cor": "India ",
      "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
      "firebaseSignInProvider": "password",
      "active": true,
      "isDeleted": false,
      "dob": "2012-02-16T00:00:00.000Z",
      "otp": 0,
      "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
      "following": [
        null
      ],
      "followers": [
        null
      ],
      "followingCount": 0,
      "followersCount": 0,
      "createdAt": "2023-01-19T13:41:21.855Z",
      "updatedAt": "2023-03-29T22:05:59.587Z",
      "firstname": "Yaman",
      "lastname": "Kumar "
    },
    "createdAt": "2023-04-03T11:23:47.150Z",
    "updatedAt": "2023-04-03T11:23:47.150Z"
  },
  "owner": null,
  "views": 0,
  "favourites": 1,
  "tokenId": "121",
  "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
  "platFormFee": 0,
  "createdAt": "2023-04-03T11:50:53.545Z",
  "updatedAt": "2023-04-03T11:55:28.882Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  double? price;
  String? externalLink;
  bool? explicitSensitive;
  bool? stats;
  int? royalty;
  String? imageURL;
  String? fileType;
  String? market;
  String? status;
  OneCollectionModelDateNftCollectionId? collectionId;
  String? owner;
  int? views;
  int? favourites;
  String? tokenId;
  String? contractAddress;
  int? platFormFee;
  String? createdAt;
  String? updatedAt;

  OneCollectionModelDateNft({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.price,
    this.externalLink,
    this.explicitSensitive,
    this.stats,
    this.royalty,
    this.imageURL,
    this.fileType,
    this.market,
    this.status,
    this.collectionId,
    this.owner,
    this.views,
    this.favourites,
    this.tokenId,
    this.contractAddress,
    this.platFormFee,
    this.createdAt,
    this.updatedAt,
  });
  OneCollectionModelDateNft.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toDouble();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    stats = json['stats'];
    royalty = json['royalty']?.toInt();
    imageURL = json['imageURL']?.toString();
    fileType = json['fileType']?.toString();
    market = json['market']?.toString();
    status = json['status']?.toString();
    collectionId = (json['collectionId'] != null) ? OneCollectionModelDateNftCollectionId.fromJson(json['collectionId']) : null;
    owner = json['owner']?.toString();
    views = json['views']?.toInt();
    favourites = json['favourites']?.toInt();
    tokenId = json['tokenId']?.toString();
    contractAddress = json['contractAddress']?.toString();
    platFormFee = json['platFormFee']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['price'] = price;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['stats'] = stats;
    data['royalty'] = royalty;
    data['imageURL'] = imageURL;
    data['fileType'] = fileType;
    data['market'] = market;
    data['status'] = status;
    if (collectionId != null) {
      data['collectionId'] = collectionId!.toJson();
    }
    data['owner'] = owner;
    data['views'] = views;
    data['favourites'] = favourites;
    data['tokenId'] = tokenId;
    data['contractAddress'] = contractAddress;
    data['platFormFee'] = platFormFee;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class OneCollectionModelDateUserKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
}
*/

  String? documentType;
  String? front;
  String? back;

  OneCollectionModelDateUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  OneCollectionModelDateUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class OneCollectionModelDateUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
  },
  "name": "",
  "walletId": "",
  "_id": "63c9488150546b2606610c11",
  "email": "yamankumar112@gmail.com",
  "userType": "admin",
  "cor": "India ",
  "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "dob": "2012-02-16T00:00:00.000Z",
  "otp": 0,
  "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
  "following": [
    null
  ],
  "followers": [
    null
  ],
  "followingCount": 0,
  "followersCount": 0,
  "createdAt": "2023-01-19T13:41:21.855Z",
  "updatedAt": "2023-03-29T22:05:59.587Z",
  "firstname": "Yaman",
  "lastname": "Kumar "
}
*/

  OneCollectionModelDateUserKyc? kyc;
  String? name;
  String? walletId;
  String? Id;
  String? email;
  String? userType;
  String? cor;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? dob;
  int? otp;
  String? selfie;

  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? firstname;
  String? lastname;

  OneCollectionModelDateUser({
    this.kyc,
    this.name,
    this.walletId,
    this.Id,
    this.email,
    this.userType,
    this.cor,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.dob,
    this.otp,
    this.selfie,

    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.firstname,
    this.lastname,
  });
  OneCollectionModelDateUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? OneCollectionModelDateUserKyc.fromJson(json['kyc']) : null;
    name = json['name']?.toString();
    walletId = json['walletId']?.toString();
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    cor = json['cor']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    dob = json['dob']?.toString();
    otp = json['otp']?.toInt();
    selfie = json['selfie']?.toString();

    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['name'] = name;
    data['walletId'] = walletId;
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['cor'] = cor;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['dob'] = dob;
    data['otp'] = otp;
    data['selfie'] = selfie;

    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class OneCollectionModelDate {
/*
{
  "_id": "642ab7435b1e596fb7376664",
  "title": "Minted queens ",
  "category": "png",
  "description": "Minted queens ",
  "externalLink": "www",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
  "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
    },
    "name": "",
    "walletId": "",
    "_id": "63c9488150546b2606610c11",
    "email": "yamankumar112@gmail.com",
    "userType": "admin",
    "cor": "India ",
    "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "dob": "2012-02-16T00:00:00.000Z",
    "otp": 0,
    "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
    "following": [
      null
    ],
    "followers": [
      null
    ],
    "followingCount": 0,
    "followersCount": 0,
    "createdAt": "2023-01-19T13:41:21.855Z",
    "updatedAt": "2023-03-29T22:05:59.587Z",
    "firstname": "Yaman",
    "lastname": "Kumar "
  },
  "volume": 0.03,
  "floorprice": 0.01,
  "noOfItems": 3,
  "latestPrice": 0.01,
  "nft": [
    {
      "_id": "642abd9d5b1e596fb7376750",
      "title": "RED ",
      "category": "png",
      "description": "desc",
      "price": 0.01,
      "externalLink": "www",
      "explicit_sensitive": true,
      "stats": true,
      "royalty": 10,
      "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_E211332C-C9DB-45C0-BC58-494A2803C75A-2281-0000010F2F506E37.jpg",
      "fileType": "image",
      "market": "setPrice",
      "status": "Listed",
      "collectionId": {
        "_id": "642ab7435b1e596fb7376664",
        "title": "Minted queens ",
        "category": "png",
        "description": "Minted queens ",
        "externalLink": "www",
        "explicit_sensitive": true,
        "royalty": 1,
        "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
        "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
        "user": {
          "kyc": {
            "documentType": "document",
            "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
            "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
          },
          "name": "",
          "walletId": "",
          "_id": "63c9488150546b2606610c11",
          "email": "yamankumar112@gmail.com",
          "userType": "admin",
          "cor": "India ",
          "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
          "firebaseSignInProvider": "password",
          "active": true,
          "isDeleted": false,
          "dob": "2012-02-16T00:00:00.000Z",
          "otp": 0,
          "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
          "following": [
            null
          ],
          "followers": [
            null
          ],
          "followingCount": 0,
          "followersCount": 0,
          "createdAt": "2023-01-19T13:41:21.855Z",
          "updatedAt": "2023-03-29T22:05:59.587Z",
          "firstname": "Yaman",
          "lastname": "Kumar "
        },
        "createdAt": "2023-04-03T11:23:47.150Z",
        "updatedAt": "2023-04-03T11:23:47.150Z"
      },
      "owner": null,
      "views": 0,
      "favourites": 1,
      "tokenId": "121",
      "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
      "platFormFee": 0,
      "createdAt": "2023-04-03T11:50:53.545Z",
      "updatedAt": "2023-04-03T11:55:28.882Z"
    }
  ],
  "noOfnft": 3
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  OneCollectionModelDateUser? user;
  double? volume;
  double? floorprice;
  int? noOfItems;
  double? latestPrice;
  List<OneCollectionModelDateNft?>? nft;
  int? noOfnft;

  OneCollectionModelDate({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.volume,
    this.floorprice,
    this.noOfItems,
    this.latestPrice,
    this.nft,
    this.noOfnft,
  });
  OneCollectionModelDate.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? OneCollectionModelDateUser.fromJson(json['user']) : null;
    volume = json['volume']?.toDouble();
    floorprice = json['floorprice']?.toDouble();
    noOfItems = json['noOfItems']?.toInt();
    latestPrice = json['latestPrice']?.toDouble();
    if (json['nft'] != null) {
      final v = json['nft'];
      final arr0 = <OneCollectionModelDateNft>[];
      v.forEach((v) {
        arr0.add(OneCollectionModelDateNft.fromJson(v));
      });
      nft = arr0;
    }
    noOfnft = json['noOfnft']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['volume'] = volume;
    data['floorprice'] = floorprice;
    data['noOfItems'] = noOfItems;
    data['latestPrice'] = latestPrice;
    if (nft != null) {
      final v = nft;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['nft'] = arr0;
    }
    data['noOfnft'] = noOfnft;
    return data;
  }
}

class OneCollectionModel {
/*
{
  "status": true,
  "message": "collection data",
  "date": {
    "_id": "642ab7435b1e596fb7376664",
    "title": "Minted queens ",
    "category": "png",
    "description": "Minted queens ",
    "externalLink": "www",
    "explicit_sensitive": true,
    "royalty": 1,
    "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
    "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
    "user": {
      "kyc": {
        "documentType": "document",
        "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
        "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
      },
      "name": "",
      "walletId": "",
      "_id": "63c9488150546b2606610c11",
      "email": "yamankumar112@gmail.com",
      "userType": "admin",
      "cor": "India ",
      "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
      "firebaseSignInProvider": "password",
      "active": true,
      "isDeleted": false,
      "dob": "2012-02-16T00:00:00.000Z",
      "otp": 0,
      "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
      "following": [
        null
      ],
      "followers": [
        null
      ],
      "followingCount": 0,
      "followersCount": 0,
      "createdAt": "2023-01-19T13:41:21.855Z",
      "updatedAt": "2023-03-29T22:05:59.587Z",
      "firstname": "Yaman",
      "lastname": "Kumar "
    },
    "volume": 0.03,
    "floorprice": 0.01,
    "noOfItems": 3,
    "latestPrice": 0.01,
    "nft": [
      {
        "_id": "642abd9d5b1e596fb7376750",
        "title": "RED ",
        "category": "png",
        "description": "desc",
        "price": 0.01,
        "externalLink": "www",
        "explicit_sensitive": true,
        "stats": true,
        "royalty": 10,
        "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_E211332C-C9DB-45C0-BC58-494A2803C75A-2281-0000010F2F506E37.jpg",
        "fileType": "image",
        "market": "setPrice",
        "status": "Listed",
        "collectionId": {
          "_id": "642ab7435b1e596fb7376664",
          "title": "Minted queens ",
          "category": "png",
          "description": "Minted queens ",
          "externalLink": "www",
          "explicit_sensitive": true,
          "royalty": 1,
          "profile": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_06EA51C5-7EEB-48B7-9F08-12C5308E70A0-2281-00000106234C878F.jpg",
          "cover": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_612BDE17-2647-438B-8047-28ED693EF3A2-2281-000001062645183B.jpg",
          "user": {
            "kyc": {
              "documentType": "document",
              "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
              "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
            },
            "name": "",
            "walletId": "",
            "_id": "63c9488150546b2606610c11",
            "email": "yamankumar112@gmail.com",
            "userType": "admin",
            "cor": "India ",
            "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
            "firebaseSignInProvider": "password",
            "active": true,
            "isDeleted": false,
            "dob": "2012-02-16T00:00:00.000Z",
            "otp": 0,
            "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
            "following": [
              null
            ],
            "followers": [
              null
            ],
            "followingCount": 0,
            "followersCount": 0,
            "createdAt": "2023-01-19T13:41:21.855Z",
            "updatedAt": "2023-03-29T22:05:59.587Z",
            "firstname": "Yaman",
            "lastname": "Kumar "
          },
          "createdAt": "2023-04-03T11:23:47.150Z",
          "updatedAt": "2023-04-03T11:23:47.150Z"
        },
        "owner": null,
        "views": 0,
        "favourites": 1,
        "tokenId": "121",
        "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
        "platFormFee": 0,
        "createdAt": "2023-04-03T11:50:53.545Z",
        "updatedAt": "2023-04-03T11:55:28.882Z"
      }
    ],
    "noOfnft": 3
  }
}
*/

  bool? status;
  String? message;
  OneCollectionModelDate? date;

  OneCollectionModel({
    this.status,
    this.message,
    this.date,
  });
  OneCollectionModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    date = (json['date'] != null) ? OneCollectionModelDate.fromJson(json['date']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (date != null) {
      data['date'] = date!.toJson();
    }
    return data;
  }
}
