///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrendingNftDataCollectionIdUserKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
}
*/

  String? documentType;
  String? front;
  String? back;

  TrendingNftDataCollectionIdUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  TrendingNftDataCollectionIdUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class TrendingNftDataCollectionIdUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
  },
  "name": "",
  "walletId": "",
  "_id": "63c9488150546b2606610c11",
  "email": "yamankumar112@gmail.com",
  "userType": "admin",
  "cor": "India ",
  "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "dob": "2012-02-16T00:00:00.000Z",
  "otp": 0,
  "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_0223D2E5-EEE3-4260-8E87-FEB1C3DAA143.jpg",
  "followingCount": 0,
  "followersCount": 0,
  "createdAt": "2023-01-19T13:41:21.855Z",
  "updatedAt": "2023-03-29T12:41:03.297Z",
  "firstname": "Yaman",
  "lastname": "Kumar "
}
*/

  TrendingNftDataCollectionIdUserKyc? kyc;
  String? name;
  String? walletId;
  String? Id;
  String? email;
  String? userType;
  String? cor;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? dob;
  int? otp;
  String? selfie;
  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? firstname;
  String? lastname;

  TrendingNftDataCollectionIdUser({
    this.kyc,
    this.name,
    this.walletId,
    this.Id,
    this.email,
    this.userType,
    this.cor,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.dob,
    this.otp,
    this.selfie,
    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.firstname,
    this.lastname,
  });
  TrendingNftDataCollectionIdUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? TrendingNftDataCollectionIdUserKyc.fromJson(json['kyc']) : null;
    name = json['name']?.toString();
    walletId = json['walletId']?.toString();
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    cor = json['cor']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    dob = json['dob']?.toString();
    otp = json['otp']?.toInt();
    selfie = json['selfie']?.toString();
    followingCount = json['followingCount']?.toInt();
    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['name'] = name;
    data['walletId'] = walletId;
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['cor'] = cor;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['dob'] = dob;
    data['otp'] = otp;
    data['selfie'] = selfie;
    data['followingCount'] = followingCount;
    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class TrendingNftDataCollectionId {
/*
{
  "_id": "6405bc5781c8351497284a80",
  "title": "collection1",
  "category": "png",
  "description": "collection description",
  "externalLink": "https://www.collection.io",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "profile link",
  "cover": "cover link",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
    },
    "name": "",
    "walletId": "",
    "_id": "63c9488150546b2606610c11",
    "email": "yamankumar112@gmail.com",
    "userType": "admin",
    "cor": "India ",
    "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "dob": "2012-02-16T00:00:00.000Z",
    "otp": 0,
    "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_0223D2E5-EEE3-4260-8E87-FEB1C3DAA143.jpg",
    "followingCount": 0,
    "followersCount": 0,
    "createdAt": "2023-01-19T13:41:21.855Z",
    "updatedAt": "2023-03-29T12:41:03.297Z",
    "firstname": "Yaman",
    "lastname": "Kumar "
  },
  "createdAt": "2023-03-06T10:11:35.414Z",
  "updatedAt": "2023-03-06T10:11:35.414Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  TrendingNftDataCollectionIdUser? user;
  String? createdAt;
  String? updatedAt;

  TrendingNftDataCollectionId({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.createdAt,
    this.updatedAt,
  });
  TrendingNftDataCollectionId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? TrendingNftDataCollectionIdUser.fromJson(json['user']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class TrendingNftData {
/*
{
  "_id": "6405c5c157a35b9247987069",
  "title": "The Bored Ape",
  "category": "png",
  "description": "Bored Ape #79 looks almost as bored as I feel when I think about NFTs (non-fungible tokens) and their supposedly seismic impact on art. My jaw slides, my eyelids hang down and I want to pick lice from my fur.",
  "price": 0.01,
  "externalLink": "qwertyui",
  "explicit_sensitive": true,
  "stats": true,
  "royalty": 3,
  "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-gallery1125.webp",
  "fileType": "image",
  "market": "setPrice",
  "status": "Listed",
  "collectionId": {
    "_id": "6405bc5781c8351497284a80",
    "title": "collection1",
    "category": "png",
    "description": "collection description",
    "externalLink": "https://www.collection.io",
    "explicit_sensitive": true,
    "royalty": 1,
    "profile": "profile link",
    "cover": "cover link",
    "user": {
      "kyc": {
        "documentType": "document",
        "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
        "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
      },
      "name": "",
      "walletId": "",
      "_id": "63c9488150546b2606610c11",
      "email": "yamankumar112@gmail.com",
      "userType": "admin",
      "cor": "India ",
      "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
      "firebaseSignInProvider": "password",
      "active": true,
      "isDeleted": false,
      "dob": "2012-02-16T00:00:00.000Z",
      "otp": 0,
      "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_0223D2E5-EEE3-4260-8E87-FEB1C3DAA143.jpg",
      "followingCount": 0,
      "followersCount": 0,
      "createdAt": "2023-01-19T13:41:21.855Z",
      "updatedAt": "2023-03-29T12:41:03.297Z",
      "firstname": "Yaman",
      "lastname": "Kumar "
    },
    "createdAt": "2023-03-06T10:11:35.414Z",
    "updatedAt": "2023-03-06T10:11:35.414Z"
  },
  "owner": null,
  "views": 0,
  "favourites": 1,
  "tokenId": "39",
  "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
  "platFormFee": 0,
  "createdAt": "2023-03-06T10:51:45.001Z",
  "updatedAt": "2023-03-29T11:43:49.792Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  double? price;
  String? externalLink;
  bool? explicitSensitive;
  bool? stats;
  int? royalty;
  String? imageURL;
  String? fileType;
  String? market;
  String? status;
  TrendingNftDataCollectionId? collectionId;
  String? owner;
  int? views;
  int? favourites;
  String? tokenId;
  String? contractAddress;
  int? platFormFee;
  String? createdAt;
  String? updatedAt;

  TrendingNftData({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.price,
    this.externalLink,
    this.explicitSensitive,
    this.stats,
    this.royalty,
    this.imageURL,
    this.fileType,
    this.market,
    this.status,
    this.collectionId,
    this.owner,
    this.views,
    this.favourites,
    this.tokenId,
    this.contractAddress,
    this.platFormFee,
    this.createdAt,
    this.updatedAt,
  });
  TrendingNftData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    price = json['price']?.toDouble();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    stats = json['stats'];
    royalty = json['royalty']?.toInt();
    imageURL = json['imageURL']?.toString();
    fileType = json['fileType']?.toString();
    market = json['market']?.toString();
    status = json['status']?.toString();
    collectionId = (json['collectionId'] != null) ? TrendingNftDataCollectionId.fromJson(json['collectionId']) : null;
    owner = json['owner']?.toString();
    views = json['views']?.toInt();
    favourites = json['favourites']?.toInt();
    tokenId = json['tokenId']?.toString();
    contractAddress = json['contractAddress']?.toString();
    platFormFee = json['platFormFee']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['price'] = price;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['stats'] = stats;
    data['royalty'] = royalty;
    data['imageURL'] = imageURL;
    data['fileType'] = fileType;
    data['market'] = market;
    data['status'] = status;
    if (collectionId != null) {
      data['collectionId'] = collectionId!.toJson();
    }
    data['owner'] = owner;
    data['views'] = views;
    data['favourites'] = favourites;
    data['tokenId'] = tokenId;
    data['contractAddress'] = contractAddress;
    data['platFormFee'] = platFormFee;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class TrendingNft {
/*
{
  "status": true,
  "message": "Trending nft's",
  "data": [
    {
      "_id": "6405c5c157a35b9247987069",
      "title": "The Bored Ape",
      "category": "png",
      "description": "Bored Ape #79 looks almost as bored as I feel when I think about NFTs (non-fungible tokens) and their supposedly seismic impact on art. My jaw slides, my eyelids hang down and I want to pick lice from my fur.",
      "price": 0.01,
      "externalLink": "qwertyui",
      "explicit_sensitive": true,
      "stats": true,
      "royalty": 3,
      "imageURL": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-gallery1125.webp",
      "fileType": "image",
      "market": "setPrice",
      "status": "Listed",
      "collectionId": {
        "_id": "6405bc5781c8351497284a80",
        "title": "collection1",
        "category": "png",
        "description": "collection description",
        "externalLink": "https://www.collection.io",
        "explicit_sensitive": true,
        "royalty": 1,
        "profile": "profile link",
        "cover": "cover link",
        "user": {
          "kyc": {
            "documentType": "document",
            "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
            "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
          },
          "name": "",
          "walletId": "",
          "_id": "63c9488150546b2606610c11",
          "email": "yamankumar112@gmail.com",
          "userType": "admin",
          "cor": "India ",
          "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
          "firebaseSignInProvider": "password",
          "active": true,
          "isDeleted": false,
          "dob": "2012-02-16T00:00:00.000Z",
          "otp": 0,
          "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_0223D2E5-EEE3-4260-8E87-FEB1C3DAA143.jpg",
          "followingCount": 0,
          "followersCount": 0,
          "createdAt": "2023-01-19T13:41:21.855Z",
          "updatedAt": "2023-03-29T12:41:03.297Z",
          "firstname": "Yaman",
          "lastname": "Kumar "
        },
        "createdAt": "2023-03-06T10:11:35.414Z",
        "updatedAt": "2023-03-06T10:11:35.414Z"
      },
      "owner": null,
      "views": 0,
      "favourites": 1,
      "tokenId": "39",
      "contractAddress": "0x81eaeC135cF1D9b3eE82bCB63Ac65766843076C0",
      "platFormFee": 0,
      "createdAt": "2023-03-06T10:51:45.001Z",
      "updatedAt": "2023-03-29T11:43:49.792Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<TrendingNftData?>? data;

  TrendingNft({
    this.status,
    this.message,
    this.data,
  });
  TrendingNft.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <TrendingNftData>[];
      v.forEach((v) {
        arr0.add(TrendingNftData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
