///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class userCollectionUsersUserKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
}
*/

  String? documentType;
  String? front;
  String? back;

  userCollectionUsersUserKyc({
    this.documentType,
    this.front,
    this.back,
  });
  userCollectionUsersUserKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class userCollectionUsersUser {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
  },
  "name": "",
  "walletId": "",
  "_id": "63c9488150546b2606610c11",
  "email": "yamankumar112@gmail.com",
  "userType": "admin",
  "cor": "India ",
  "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "dob": "2012-02-16T00:00:00.000Z",
  "otp": 0,
  "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
  "followingCount": 0,
  "followersCount": 0,
  "createdAt": "2023-01-19T13:41:21.855Z",
  "updatedAt": "2023-03-29T22:05:59.587Z",
  "firstname": "Yaman",
  "lastname": "Kumar "
}
*/

  userCollectionUsersUserKyc? kyc;
  String? name;
  String? walletId;
  String? Id;
  String? email;
  String? userType;
  String? cor;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? dob;
  int? otp;
  String? selfie;
  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? firstname;
  String? lastname;

  userCollectionUsersUser({
    this.kyc,
    this.name,
    this.walletId,
    this.Id,
    this.email,
    this.userType,
    this.cor,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.dob,
    this.otp,
    this.selfie,
    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.firstname,
    this.lastname,
  });
  userCollectionUsersUser.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? userCollectionUsersUserKyc.fromJson(json['kyc']) : null;
    name = json['name']?.toString();
    walletId = json['walletId']?.toString();
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    cor = json['cor']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    dob = json['dob']?.toString();
    otp = json['otp']?.toInt();
    selfie = json['selfie']?.toString();
    followingCount = json['followingCount']?.toInt();
    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['name'] = name;
    data['walletId'] = walletId;
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['cor'] = cor;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['dob'] = dob;
    data['otp'] = otp;
    data['selfie'] = selfie;
    data['followingCount'] = followingCount;
    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class userCollectionUsers {
/*
{
  "_id": "6405bc5781c8351497284a80",
  "title": "collection1",
  "category": "png",
  "description": "collection description",
  "externalLink": "https://www.collection.io",
  "explicit_sensitive": true,
  "royalty": 1,
  "profile": "profile link",
  "cover": "cover link",
  "user": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
    },
    "name": "",
    "walletId": "",
    "_id": "63c9488150546b2606610c11",
    "email": "yamankumar112@gmail.com",
    "userType": "admin",
    "cor": "India ",
    "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "dob": "2012-02-16T00:00:00.000Z",
    "otp": 0,
    "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
    "followingCount": 0,
    "followersCount": 0,
    "createdAt": "2023-01-19T13:41:21.855Z",
    "updatedAt": "2023-03-29T22:05:59.587Z",
    "firstname": "Yaman",
    "lastname": "Kumar "
  },
  "createdAt": "2023-03-06T10:11:35.414Z",
  "updatedAt": "2023-03-06T10:11:35.414Z"
}
*/

  String? Id;
  String? title;
  String? category;
  String? description;
  String? externalLink;
  bool? explicitSensitive;
  int? royalty;
  String? profile;
  String? cover;
  userCollectionUsersUser? user;
  String? createdAt;
  String? updatedAt;

  userCollectionUsers({
    this.Id,
    this.title,
    this.category,
    this.description,
    this.externalLink,
    this.explicitSensitive,
    this.royalty,
    this.profile,
    this.cover,
    this.user,
    this.createdAt,
    this.updatedAt,
  });
  userCollectionUsers.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    category = json['category']?.toString();
    description = json['description']?.toString();
    externalLink = json['externalLink']?.toString();
    explicitSensitive = json['explicit_sensitive'];
    royalty = json['royalty']?.toInt();
    profile = json['profile']?.toString();
    cover = json['cover']?.toString();
    user = (json['user'] != null) ? userCollectionUsersUser.fromJson(json['user']) : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['category'] = category;
    data['description'] = description;
    data['externalLink'] = externalLink;
    data['explicit_sensitive'] = explicitSensitive;
    data['royalty'] = royalty;
    data['profile'] = profile;
    data['cover'] = cover;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class userCollection {
/*
{
  "status": true,
  "results": 1,
  "message": "all Collection",
  "users": [
    {
      "_id": "6405bc5781c8351497284a80",
      "title": "collection1",
      "category": "png",
      "description": "collection description",
      "externalLink": "https://www.collection.io",
      "explicit_sensitive": true,
      "royalty": 1,
      "profile": "profile link",
      "cover": "cover link",
      "user": {
        "kyc": {
          "documentType": "document",
          "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
          "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
        },
        "name": "",
        "walletId": "",
        "_id": "63c9488150546b2606610c11",
        "email": "yamankumar112@gmail.com",
        "userType": "admin",
        "cor": "India ",
        "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
        "firebaseSignInProvider": "password",
        "active": true,
        "isDeleted": false,
        "dob": "2012-02-16T00:00:00.000Z",
        "otp": 0,
        "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_98AACC1D-9823-435F-868F-0526AFB53D81.jpg",
        "followingCount": 0,
        "followersCount": 0,
        "createdAt": "2023-01-19T13:41:21.855Z",
        "updatedAt": "2023-03-29T22:05:59.587Z",
        "firstname": "Yaman",
        "lastname": "Kumar "
      },
      "createdAt": "2023-03-06T10:11:35.414Z",
      "updatedAt": "2023-03-06T10:11:35.414Z"
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<userCollectionUsers?>? users;

  userCollection({
    this.status,
    this.results,
    this.message,
    this.users,
  });
  userCollection.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['users'] != null) {
      final v = json['users'];
      final arr0 = <userCollectionUsers>[];
      v.forEach((v) {
        arr0.add(userCollectionUsers.fromJson(v));
      });
      users = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (users != null) {
      final v = users;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['users'] = arr0;
    }
    return data;
  }
}
