///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModelDataKyc {
/*
{
  "documentType": "document",
  "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
  "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
}
*/

  String? documentType;
  String? front;
  String? back;

  UserModelDataKyc({
    this.documentType,
    this.front,
    this.back,
  });
  UserModelDataKyc.fromJson(Map<String, dynamic> json) {
    documentType = json['documentType']?.toString();
    front = json['front']?.toString();
    back = json['back']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['documentType'] = documentType;
    data['front'] = front;
    data['back'] = back;
    return data;
  }
}

class UserModelData {
/*
{
  "kyc": {
    "documentType": "document",
    "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
    "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
  },
  "name": "",
  "walletId": "",
  "_id": "63c9488150546b2606610c11",
  "email": "yamankumar112@gmail.com",
  "userType": "admin",
  "cor": "India ",
  "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
  "firebaseSignInProvider": "password",
  "active": true,
  "isDeleted": false,
  "dob": "2012-02-16T00:00:00.000Z",
  "otp": 0,
  "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_679682AF-8FA5-44AE-A23F-2B1E759B8608.jpg",
  "followingCount": 0,
  "followersCount": 0,
  "createdAt": "2023-01-19T13:41:21.855Z",
  "updatedAt": "2023-03-28T14:57:02.586Z",
  "firstname": "Yaman",
  "lastname": "Kumar "
}
*/

  UserModelDataKyc? kyc;
  String? name;
  String? walletId;
  String? Id;
  String? email;
  String? userType;
  String? cor;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? dob;
  int? otp;
  String? selfie;
  int? followingCount;
  int? followersCount;
  String? createdAt;
  String? updatedAt;
  String? firstname;
  String? lastname;

  UserModelData({
    this.kyc,
    this.name,
    this.walletId,
    this.Id,
    this.email,
    this.userType,
    this.cor,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.dob,
    this.otp,
    this.selfie,
    this.followingCount,
    this.followersCount,
    this.createdAt,
    this.updatedAt,
    this.firstname,
    this.lastname,
  });
  UserModelData.fromJson(Map<String, dynamic> json) {
    kyc = (json['kyc'] != null) ? UserModelDataKyc.fromJson(json['kyc']) : null;
    name = json['name']?.toString();
    walletId = json['walletId']?.toString();
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    userType = json['userType']?.toString();
    cor = json['cor']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    dob = json['dob']?.toString();
    otp = json['otp']?.toInt();
    selfie = json['selfie']?.toString();
    followingCount = json['followingCount']?.toInt();
    followersCount = json['followersCount']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    firstname = json['firstname']?.toString();
    lastname = json['lastname']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kyc != null) {
      data['kyc'] = kyc!.toJson();
    }
    data['name'] = name;
    data['walletId'] = walletId;
    data['_id'] = Id;
    data['email'] = email;
    data['userType'] = userType;
    data['cor'] = cor;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['dob'] = dob;
    data['otp'] = otp;
    data['selfie'] = selfie;
    data['followingCount'] = followingCount;
    data['followersCount'] = followersCount;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['firstname'] = firstname;
    data['lastname'] = lastname;
    return data;
  }
}

class UserModel {
/*
{
  "status": true,
  "message": "user details",
  "data": {
    "kyc": {
      "documentType": "document",
      "front": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_3065F9DB-51C1-4BF7-A478-37B190D6E405-22249-000007656E292105.png",
      "back": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryimage_picker_32C5FA95-56E3-445F-9D89-79F50F4DB911-22249-000007656B39B2DF.png"
    },
    "name": "",
    "walletId": "",
    "_id": "63c9488150546b2606610c11",
    "email": "yamankumar112@gmail.com",
    "userType": "admin",
    "cor": "India ",
    "firebaseUid": "ySSPaOkeibWRl6VbpB9KaWVP7fL2",
    "firebaseSignInProvider": "password",
    "active": true,
    "isDeleted": false,
    "dob": "2012-02-16T00:00:00.000Z",
    "otp": 0,
    "selfie": "https://salvatara.s3.us-east-2.amazonaws.com/salvatara-galleryCAP_679682AF-8FA5-44AE-A23F-2B1E759B8608.jpg",
    "followingCount": 0,
    "followersCount": 0,
    "createdAt": "2023-01-19T13:41:21.855Z",
    "updatedAt": "2023-03-28T14:57:02.586Z",
    "firstname": "Yaman",
    "lastname": "Kumar "
  }
}
*/

  bool? status;
  String? message;
  UserModelData? data;

  UserModel({
    this.status,
    this.message,
    this.data,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? UserModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
